const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');

const source = fs.readFileSync(path.join(__dirname, '../dist/game.js'), 'utf8');
const start = source.indexOf('  const roundMoney =');
const end = source.indexOf('  const toast =', start);
assert(start > 0 && end > start, 'loan calculation block exists');

const state = {companyLevel:1, assets:180, loan:{principal:0, interestDue:0}};
const context = {state};
vm.createContext(context);
vm.runInContext(source.slice(start, end) + '\nthis.loanApi={loanLimit,loanRate,loanBalance,availableLoan,borrowLoan,repayLoan,accrueLoanInterest};', context);
const {loanLimit,loanRate,loanBalance,availableLoan,borrowLoan,repayLoan,accrueLoanInterest} = context.loanApi;

assert.equal(loanLimit(1), 60);
assert.equal(loanLimit(10), 420);
assert.equal(Number(loanRate(1).toFixed(3)), .08);
assert.equal(Number(loanRate(10).toFixed(3)), .035);
assert.equal(availableLoan(), 60);
assert.equal(borrowLoan(61), false);
assert.equal(borrowLoan(1.5), false);
assert.equal(borrowLoan(60), true);
assert.equal(state.assets, 240);
assert.equal(state.loan.principal, 60);
assert.equal(availableLoan(), 0);
assert.equal(accrueLoanInterest(), 4.8);
assert.equal(loanBalance(), 64.8);
assert.equal(repayLoan(2.3), true);
assert.equal(state.loan.interestDue, 2.5);
assert.equal(state.loan.principal, 60);
assert.equal(repayLoan(5), true);
assert.equal(state.loan.interestDue, 0);
assert.equal(state.loan.principal, 57.5);
state.companyLevel = 2;
assert.equal(availableLoan(), 42);
assert.equal(borrowLoan(42), true);
assert.equal(state.loan.principal, 99.5);
assert.equal(Number(loanRate(2).toFixed(3)), .075);
assert.equal(repayLoan(loanBalance() + .1), false);
state.assets = 0;
assert.equal(repayLoan(1), false);
state.assets = 200;
assert.equal(repayLoan(loanBalance()), true);
assert.equal(loanBalance(), 0);
assert.equal(accrueLoanInterest(), 0);
assert.equal(state.loan.principal, 0);
assert.equal(state.loan.interestDue, 0);
console.log('Loan limits, level rates, seasonal interest, partial/full repayment, and bounds passed.');
