const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');

const source=fs.readFileSync(path.join(__dirname,'../dist/client/game.js'),'utf8');
const start=source.indexOf('  const researchProjects=');
const end=source.indexOf('  const showResearch =',start);
assert(start>0&&end>start);
const state={research:12,researchTasks:[],unlocks:[],monthsElapsed:0};
const context={state,has:id=>state.unlocks.includes(id)};
vm.createContext(context);
vm.runInContext(source.slice(start,end)+'\nthis.api={researchProjects,researchDuration,startResearch,finishResearch};',context);
const {researchProjects,researchDuration,startResearch,finishResearch}=context.api;
const linen=researchProjects['소재'][0];
const silhouette=researchProjects['의류'][1];
assert.equal(researchDuration(linen),2);
assert.equal(researchDuration(silhouette),5);
assert.equal(startResearch(linen),true);
assert.equal(state.research,8);
assert.equal(startResearch(linen),false);
state.monthsElapsed=1;
assert.equal(finishResearch().length,0);
assert.equal(context.has(linen.id),false);
state.monthsElapsed=2;
assert.equal(finishResearch().join(','),'리넨 소재');
assert.equal(context.has(linen.id),true);
assert.equal(startResearch(silhouette),true);
assert.equal(state.research,1);
state.monthsElapsed=6;
assert.equal(finishResearch().length,0);
state.monthsElapsed=7;
assert.equal(finishResearch().join(','),'실루엣 연구');
assert.equal(context.has(silhouette.id),true);
assert.equal(state.researchTasks.length,0);
context.baseCategories=['티셔츠','셔츠','바지','원피스','아우터'];
context.styles=['미니멀','스트리트','클래식','러블리','아웃도어'];
const choices=source.slice(source.indexOf('  const unlockedOptions='),source.indexOf('  const levelBonus ='));
vm.runInContext(choices+'\nthis.choices={availableItems,availableMaterials,availableStyles};',context);
assert.equal(context.choices.availableMaterials().includes('리오셀'),false);
assert.equal(context.choices.availableItems().includes('코트'),false);
assert.equal(context.choices.availableStyles().includes('프레피'),false);
state.research=30;
for(const project of [researchProjects['소재'].find(item=>item.id==='regeneratedResearch'),researchProjects['의류'].find(item=>item.id==='outerwearResearch'),researchProjects['스타일'].find(item=>item.id==='formalStyle')])assert.equal(startResearch(project),true);
assert.equal(context.choices.availableMaterials().includes('리오셀'),false);
state.monthsElapsed=13;
assert.equal(finishResearch().length,3);
assert.equal(context.choices.availableMaterials().includes('리오셀'),true);
assert.equal(context.choices.availableItems().includes('코트'),true);
assert.equal(context.choices.availableStyles().includes('프레피'),true);
const match=source.slice(source.indexOf('  const materialMatch='),source.indexOf('  const collectionTrial ='));
vm.runInContext(match+'\nthis.materialMatch=materialMatch;',context);
assert.equal(context.materialMatch({material:'울',item:'코트',style:'포멀'},{season:'겨울'}),true);
assert.equal(context.materialMatch({material:'울',item:'코트',style:'포멀'},{season:'여름'}),false);
console.log('Research spends points at start, finishes after the right game months, and unlocks only on completion.');
